# Generated by Django 2.2 on 2019-11-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('prediction_level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('prediction_level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Legroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('prediction_level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Timeliness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('prediction_level', models.CharField(max_length=20)),
            ],
        ),
    ]
