# Generated by Django 2.2.7 on 2020-07-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191106_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('prediction_level', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='AvailabilityBadModel',
        ),
        migrations.DeleteModel(
            name='AvailabilityGoodModel',
        ),
    ]
