# Generated by Django 2.2.7 on 2020-07-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200701_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitymodel',
            name='tweet_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
