# Generated by Django 2.2.7 on 2020-07-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_availabilitymodel_tweet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('prediction_level', models.CharField(max_length=20)),
            ],
        ),
    ]
