# Generated by Django 2.2.7 on 2020-07-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_aggregatemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('prediction_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LegroomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('prediction_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TimelinessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('prediction_level', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CostBadModel',
        ),
        migrations.DeleteModel(
            name='CostGoodModel',
        ),
        migrations.DeleteModel(
            name='LegroomBadModel',
        ),
        migrations.DeleteModel(
            name='LegroomGoodModel',
        ),
        migrations.DeleteModel(
            name='TimelinessBadModel',
        ),
        migrations.DeleteModel(
            name='TimelinessGoodModel',
        ),
    ]
