# Generated by Django 2.2.7 on 2020-07-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200701_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCondensedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('prediction_level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LegroomCondensedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('prediction_level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TimelinessCondensedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('prediction_level', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='AggregateModel',
            new_name='AvailabilityCondensedModel',
        ),
    ]
