# Generated by Django 2.2.7 on 2020-07-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200701_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='JetblueAggregateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('prediction_level', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='AvailabilityCondensedModel',
        ),
        migrations.DeleteModel(
            name='CostCondensedModel',
        ),
        migrations.DeleteModel(
            name='LegroomCondensedModel',
        ),
        migrations.DeleteModel(
            name='TimelinessCondensedModel',
        ),
    ]
