# Generated by Django 2.2.7 on 2020-07-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200702_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='JetblueCondensedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('average_prediction', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='AvailabilityModel',
        ),
        migrations.DeleteModel(
            name='CostModel',
        ),
        migrations.DeleteModel(
            name='LegroomModel',
        ),
        migrations.DeleteModel(
            name='TimelinessModel',
        ),
        migrations.AddField(
            model_name='jetblueaggregatemodel',
            name='link',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='jetblueaggregatemodel',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jetblueaggregatemodel',
            name='text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='jetblueaggregatemodel',
            name='tweet_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
