# Generated by Django 2.2.7 on 2020-07-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200702_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmericanAggregateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField(default=0)),
                ('name', models.CharField(default='', max_length=255)),
                ('text', models.CharField(default='', max_length=1000)),
                ('link', models.CharField(default='', max_length=1000)),
                ('date', models.DateTimeField()),
                ('prediction_level', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AmericanCondensedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('average_prediction', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpiritAggregateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField(default=0)),
                ('name', models.CharField(default='', max_length=255)),
                ('text', models.CharField(default='', max_length=1000)),
                ('link', models.CharField(default='', max_length=1000)),
                ('date', models.DateTimeField()),
                ('prediction_level', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpiritCondensedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('average_prediction', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UnitedAggregateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField(default=0)),
                ('name', models.CharField(default='', max_length=255)),
                ('text', models.CharField(default='', max_length=1000)),
                ('link', models.CharField(default='', max_length=1000)),
                ('date', models.DateTimeField()),
                ('prediction_level', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UnitedCondensedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('average_prediction', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
