from django.core.management import call_command

# American Airlines crons
call_command('americanAvailable')
call_command('americanBaggageFees')
call_command('americanConnections')
call_command('americanCost')
call_command('americanFamilyOptions')
call_command('americanFoodEntertainment')
call_command('americanHiddenFees')
call_command('americanLegroom')
call_command('americanReimbursement')
call_command('americanService')
call_command('americanTime')
call_command('americanTravelRewards')

# JetBlue crons
call_command('jetblueAvailable')
call_command('jetblueBaggageFees')
call_command('jetbluenConnections')
call_command('jetblueCost')
call_command('jetblueFamilyOptions')
call_command('jetblueFoodEntertainment')
call_command('jetblueHiddenFees')
call_command('jetblueLegroom')
call_command('jetblueReimbursement')
call_command('jetblueService')
call_command('jetblueTime')
call_command('jetblueTravelRewards')

# Spirit crons
call_command('spiritAvailable')
call_command('spiritBaggageFees')
call_command('spiritConnections')
call_command('spiritCost')
call_command('spiritFamilyOptions')
call_command('spiritFoodEntertainment')
call_command('spiritHiddenFees')
call_command('spiritLegroom')
call_command('spiritReimbursement')
call_command('spiritService')
call_command('spiritTime')
call_command('spiritTravelRewards')

# United crons
call_command('unitedAvailable')
call_command('unitedBaggageFees')
call_command('unitedConnections')
call_command('unitedCost')
call_command('unitedFamilyOptions')
call_command('unitedFoodEntertainment')
call_command('unitedHiddenFees')
call_command('unitedLegroom')
call_command('unitedReimbursement')
call_command('unitedService')
call_command('unitedTime')
call_command('unitedTravelRewards')